
      - name: Instalar Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses
      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Gerar APK
        working-directory: android
        run: |
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Trilha-do-Saber-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk